AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  Exclude:
    - 'vendor/**/*'
    - 'lib/hanami/assets/compressors/*'
    - 'test/fixtures/**/*.gemspec'
Metrics/LineLength:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/MethodMissing:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
