Metrics/LineLength:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/MethodMissing:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'lib/hanami/assets/compressors/*'
