language: ruby
script: 'bundle exec rake test:coverage --trace'
rvm:
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - 2.1.3
  - 2.1.4
  - 2.1.5
  - 2.1.6
  - 2.2.0
  - 2.2.1
  - 2.2.2
  - rbx-2

matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="--2.0"
    - rvm: jruby-head
      env: JRUBY_OPTS="--2.1"
  allow_failures:
    - rvm: 2.2
    - rvm: rbx-2
    - rvm: jruby
    - rvm: jruby-head
